name: shrine
description: Discover how Material Components for Flutter make it easy to differentiate your product and express your brand through design.

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.5
  shrine_images: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  # TODO: Insert Fonts (103)
  uses-material-design: true
  assets:
    - assets/diamond.png
    # TODO: Add slanted menu asset (104)
    - assets/0-0.jpg
